//
//  ProfileTable.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class ProfileTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _address: String?
    var _date: NSNumber?
    var _email: String?
    var _name: String?
    var _phone: String?
    var _team: String?
    
    class func dynamoDBTableName() -> String {

        return "semina-mobilehub-337334808-profileTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_address" : "address",
               "_date" : "date",
               "_email" : "email",
               "_name" : "name",
               "_phone" : "phone",
               "_team" : "team",
        ]
    }
}
