//
//  Profiles.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Profiles: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _date: NSNumber?
    @objc var _address: String?
    @objc var _email: String?
    @objc var _name: String?
    @objc var _phone: String?
    @objc var _team: String?
    @objc var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "semina-mobilehub-337334808-profiles"
    }
    
    class func hashKeyAttribute() -> String {

        return "_date"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_date" : "date",
               "_address" : "address",
               "_email" : "email",
               "_name" : "name",
               "_phone" : "phone",
               "_team" : "team",
               "_userId" : "userId",
        ]
    }
}
